on:
  push:
    branches:
      - main

jobs:

  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build foo
        run: |
          go build -o foo
          ./foo
    